In [1]:
## Threshold Function

import numpy as np
def threshold_function(x):
    y = x > 0
    return y.astype(int)

x = np.array([-1, 1, 2])
threshold_function(x)

array([0, 1, 1])

In [2]:
## Sigmoid Function

def sigmoid_function(x):
    return 1/(1+np.exp(-x))

sigmoid_function(x)

array([0.26894142, 0.73105858, 0.88079708])

In [3]:
## Tangent Function

def tangent_functiono(x):
    return (1 - np.exp(-2*x))/(1+np.exp(-2*x))

tangent_functiono(x)

array([-0.76159416,  0.76159416,  0.96402758])

In [4]:
np.tanh(x)

array([-0.76159416,  0.76159416,  0.96402758])

In [6]:
## relu function

def relu_function(x):
    return np.maximum(0, x)

relu_function(x)

array([0, 1, 2])