## 单层神经网络前向传播过程

In [1]:
import numpy as np
X = np.array([1, 2])
W = np.array([[1, 3, 5], [2, 4, 6]])
Y = np.dot(X, W)
Y

array([ 5, 11, 17])

# 两层神经网络前向传播过程

## 初始化神经网络

In [2]:
network = {}
network['w1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
network['b1'] = np.array([0.1, 0.2, 0.3])
network['w2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
network['b2'] = np.array([0.1, 0.2])

## 计算传递过程 

In [9]:
x = np.array([1, 0.5])
a = np.dot(x, network['w1']) + network['b1']

def sigmoid_function(x):
    return 1/(1 + np.exp(-x))

z1 = sigmoid_function(a)
y = np.dot(z1, network['w2']) + network['b2']
y

array([0.51615984, 1.21402696])

# Softmax Function

In [11]:
def softmax_function(x):
    return np.exp(x) / np.sum(np.exp(x))

softmax_function(y)

array([0.33228528, 0.66771472])

In [12]:
np.sum(softmax_function(y))

1.0